name: API Automation JAVA + Maven

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
  test:
    name : Test API AUTOMATION
    runs-on: ubuntu-latest
    steps:
        - name: Test API
          run: mvn clean verify